# Generated by Django 2.2.4 on 2021-12-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOpened',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_start', models.IntegerField()),
                ('day_end', models.IntegerField()),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Restuarant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hours', models.ManyToManyField(to='restuarant_api.DaysOpened')),
            ],
        ),
    ]
