# Generated by Django 2.2.4 on 2021-12-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_value', models.IntegerField()),
                ('day_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='daysopened',
            name='day_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_day', to='restuarant_api.Days'),
        ),
        migrations.AlterField(
            model_name='daysopened',
            name='day_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_day', to='restuarant_api.Days'),
        ),
    ]
