# Generated by Django 2.2.4 on 2021-12-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant_api', '0002_auto_20211215_0943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Days',
            new_name='Day',
        ),
    ]
