# Generated by Django 2.2.4 on 2021-12-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant_api', '0003_auto_20211215_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restuarant',
            name='hours',
        ),
        migrations.DeleteModel(
            name='DaysOpened',
        ),
        migrations.DeleteModel(
            name='Restuarant',
        ),
    ]
