# Generated by Django 2.2.4 on 2021-12-15 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant_api', '0004_auto_20211215_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
                ('day_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_day', to='restuarant_api.Day')),
                ('day_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_day', to='restuarant_api.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Restuarant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hours', models.ManyToManyField(to='restuarant_api.OpenDays')),
            ],
        ),
    ]
