# Generated by Django 2.2.4 on 2021-12-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant_api', '0005_opendays_restuarant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restuarant',
            name='hours',
            field=models.ManyToManyField(related_name='hours_opened', to='restuarant_api.OpenDays'),
        ),
    ]
