# Generated by Django 2.2.4 on 2021-12-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant_api', '0006_auto_20211215_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendays',
            name='time_close',
            field=models.CharField(max_length=255),
        ),
    ]
