# Generated by Django 2.2.4 on 2021-12-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant_api', '0007_auto_20211215_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendays',
            name='time_open',
            field=models.CharField(max_length=255),
        ),
    ]
